### ISSUE TITLE
 More resources are used when project is rebuilt and synthesised

### ISSUE THREAD

**Issue by jianyi324** [Siudya/ORB_FPGA#1]
Would you do me a favor? I need some help.
It costed 139115 luts  when the file called comDescriptor.cpp was synthesised.
I followed your steps to  rebuild vivado project， but i failed.
Thanks!

**Comment by Siudya** [comment]
It doesn't matter. After implement and routing, it would be optimized. It would cost about 9000+ LUT.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jianyi324"<notifications@github.com&gt;; 
发送时间: 2020年7月25日(星期六) 晚上8:37
收件人: "Siudya/ORB_FPGA"<ORB_FPGA@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [Siudya/ORB_FPGA]  More resources are used when project is rebuilt and synthesised (#1)





 
Would you do me a favor? I need some help.
 It costed 139115 luts  when the file called comDescriptor.cpp was synthesised.
 I followed your steps to  rebuild vivado project， but i failed.
 Thanks!

**Comment by jianyi324** [comment]
555... I'm confused!
Could you give me your email? I  want to show you my picture about vivado project!
Thanks!

**Comment by Siudya** [comment]
555.... 一开口就知道是中国人了 liangsen741@qq.com 你发这个吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jianyi324"<notifications@github.com&gt;; 
发送时间: 2020年7月25日(星期六) 晚上9:30
收件人: "Siudya/ORB_FPGA"<ORB_FPGA@noreply.github.com&gt;; 
抄送: "梁森"<liangsen741@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Siudya/ORB_FPGA]  More resources are used when project is rebuilt and synthesised (#1)





 
555... I'm confused!
 Could you give me your email? I  want to show you my picture about vivado project!
 Thanks!

**Comment by jianyi324** [comment]
Thank you very much!

**Comment by albert7070** [comment]
![comDescriptor_result](https://user-images.githubusercontent.com/45425017/89723708-62400380-da2c-11ea-8d99-935fee9b12d0.png)
I encountered the same problem, old brother.
During comDescriptor synthesis, the Summary showed that the available resources FF and LUT on the chip exceeded a lot. 
as the picture shows:

**Comment by Siudya** [comment]
It doesn't matter. After implementing the cost will be optimized down to an acceptable level.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Albert"<notifications@github.com&gt;; 
发送时间: 2020年8月9日(星期天) 上午10:39
收件人: "Siudya/ORB_FPGA"<ORB_FPGA@noreply.github.com&gt;; 
抄送: "梁森"<liangsen741@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Siudya/ORB_FPGA]  More resources are used when project is rebuilt and synthesised (#1)





 

 I encountered the same problem, old brother.
 During comDescriptor synthesis, the Summary showed that the available resources FF and LUT on the chip exceeded a lot.
 as the picture shows:

**Comment by albert7070** [comment]
According to the code, I have copied the .bit and .hwh files to the corresponding locations. Then, a problem occurred.
First, the .bit file is successfully loaded, and you can see that the overlay object has 4 IP Blocks: 
axi_dma_FAST; axi_dma_Gaus; axi_dma_des_2Mem; axi_intc_0.
![Jupyter_error1](https://user-images.githubusercontent.com/45425017/90131810-542d1280-dd9f-11ea-99a0-2b4d9c6ba2c7.png)
However, when calling IP Blocks whose type is pynq.lib.dma.DMA, an error will occur (take FAST as an example):
![Jupyter_error2](https://user-images.githubusercontent.com/45425017/90131976-92c2cd00-dd9f-11ea-8b6c-01c6898715cb.png)
![Jupyter_error3](https://user-images.githubusercontent.com/45425017/90131981-948c9080-dd9f-11ea-8649-8943c88de225.png)
Have you encountered similar problems? my old brother.

**Comment by Siudya** [comment]
Sorry but I never encounter the problem. Did you use pynq 2.4 or higher with the .bit and .hwh files provided in the repo? Maybe a rebooting can make it work :P .




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Albert"<notifications@github.com&gt;; 
发送时间: 2020年8月13日(星期四) 晚上8:13
收件人: "Siudya/ORB_FPGA"<ORB_FPGA@noreply.github.com&gt;; 
抄送: "梁森"<liangsen741@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Siudya/ORB_FPGA]  More resources are used when project is rebuilt and synthesised (#1)





 
According to the code, I have copied the .bit and .hwh files to the corresponding locations. Then, a problem occurred.
 First, the .bit file is successfully loaded, and you can see that the overlay object has 4 IP Blocks:
 axi_dma_FAST; axi_dma_Gaus; axi_dma_des_2Mem; axi_intc_0.
 
 However, when calling IP Blocks whose type is pynq.lib.dma.DMA, an error will occur (take FAST as an example):
 
 
 Have you encountered similar problems? my old brother.

**Comment by Silentstreet** [comment]
@albert7070 我也碰到了这个问题。但是如果是加载他的bit的话，就可以。但是自己重建的vivado工程产生的bit就没法加载出来。有意交流的话可以邮箱fastcorner@163.com。

**Comment by albert7070** [comment]
old brother,Sorry to disturb you.
I could not find the constraint xdc file of the vivado project in the pynq_arch folder. I really want to figure out how the pin constraints of your project are allocated.

**Comment by Siudya** [comment]
No contraints are needed. All the pins are set via board files. (only sysclk is connected to a PL pin)
