### ISSUE TITLE
Does the code here support NPC >1?

### ISSUE THREAD

**Issue by JianmingTONG** [Siudya/ORB_FPGA#2]
I found several lines below, and it seems that the original code 
``` 
469		if(NPC == XF_NPPC8)
470		{
471		}
```

If NPC equals XF_NPPC8, the module will have no output. And in the else branch, the code only implements one pixel's judgement. Similar operations could be seen in other module.

**Comment by Siudya** [comment]
My codes are based on XfOpencv and reserve the structure ( FAST.hpp actually ). XfOpencv supports processing 8 pixels a time, but my design does not as the resources on xc7z020 is limited and doing so may lower the frequency. Sorry for the bad coding style and I hope it doesn't bother you much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jianming"<notifications@github.com&gt;; 
发送时间: 2020年7月31日(星期五) 下午2:26
收件人: "Siudya/ORB_FPGA"<ORB_FPGA@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [Siudya/ORB_FPGA] Does the code here support NPC &gt;1? (#2)





 
I found several lines below, and it seems that the original code
 469		if(NPC == XF_NPPC8) 470		{ 471		}  
If NPC equals XF_NPPC8, the module will have no output. And in the else branch, the code only implements one pixel's judgement. Similar operations could be seen in other module.

**Comment by JianmingTONG** [comment]
Thanks for the reply and your open-source code. I study lots of tricks & templates on using xfOpencv.
