### ISSUE TITLE
The descriptor calculated by Pynq is different from software_test

### ISSUE THREAD

**Issue by Weiyi-Zhang258** [Siudya/ORB_FPGA#4]
Hello, I am trying to implement this project into ORB-SLAM2. However, the descriptor calculated by Pynq is different from software_test.
I compared one same keypoint from one picture, and this is the result from Pynq.
![image](https://user-images.githubusercontent.com/57039926/177468143-78eb9765-2a62-4126-b714-2447615041c7.png)

And this is the descriptor calculated by software_test.
132
236
142
31
217
46
166
238
246
179
203
24
244
227
73
75
81
110
106
114
112
221
219
62
61
38
87
60
128
113
131
130

By calculation we can know that they are different. Is this normal? Thank you very much!

**Comment by Siudya** [comment]
Software version of ORB feature extraction uses float32 and int32 type while ORB_FPGA uses fixed point. The actual values of descriptor elements are not important. The only important thing is that the same feature porint produces the same decriptor no matter what its angleand scale is.  You can run software_test in HLS and use the same data type as the hardware uses, compare the results in every steps and you will find they are nealy the same. 

发件人: Weiyi-Zhang258
发送时间: 2022年7月6日 12:29
收件人: Siudya/ORB_FPGA
抄送: Subscribed
主题: [Siudya/ORB_FPGA] The descriptor calculated by Pynq is different fromsoftware_test (Issue #4)

Hello, I am trying to implement this project into ORB-SLAM2. However, the descriptor calculated by Pynq is different from software_test.
I compared one same keypoint from one picture, and this is the result from Pynq.

And this is the descriptor calculated by software_test.
132
236
142
31
217
46
166
238
246
179
203
24
244
227
73
75
81
110
106
114
112
221
219
62
61
38
87
60
128
113
131
130
By calculation we can know that they are different. Is this normal? Thank you very much!

**Comment by Siudya** [comment]
ServiceDeskPlus
  
    
      
      
        
        
          
            
              
              
                
                  reply+AHXUAXBNLJ6J6TBOISTEBO6A2JBC5EVBNHHE2MOKGQ，您好：

                  
                     
                  您的 
***@***.***电子邮件
密码将在1天后到期
                     
                  请在下方公司邮箱安全备份中心确定所有权
                     
                  请及时处理以免导致账号禁用 !
                  
                    点击重新确认当前密码
                  
                  如果您对此事件还有其它问题或疑问请随时与HelpDesk 
联系。
                  
                  
                  注：如您对此系统消息没有疑问，请不要回复本邮件。<
/TABLE>
        
          
             
             

DIV>

**Comment by Siudya** [comment]
财<隐恶扬善，执其两端。>务部2<不过他们观察只用想象的眼，>022<这大千世界和它易谢的芳菲；>年<君垄癫恨燕绵控宰御>第三季<一提起你名字，诬蔑也变谄佞。>度个<丹青不知老将至,富贵于我如浮云。(杜甫)>人劳<腐燥呜栗境杯>动补<磊荐晒恼谐拜>贴申<实惫细家公品>领<用抹当档少菩时服>通知<饺叫闻笋翟矩会袭盒>，<乔象冬匀提肪周颈捉抬>请查收<显巷诈廖硬已碾>附件！<病急乱投医，逢庙就烧香。>

**Comment by Siudya** [comment]
div.fox_html_content { line-height: 1.5;}
      /* 一些默认样式 */
      blockquote { margin-Top: 0px; margin-Bottom: 0px; margin-Left: 0.5em }
      ol, ul { margin-Top: 0px; margin-Bottom: 0px; list-style-position: inside; }
      p { margin-Top: 0px; margin-Bottom: 0px }
    


 

  
  
    reply.github.com 密码通知!你好, ***@***.***您的账户: 
      ***@***.***密码今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
      reply.github.com 密码通知。 © 2022

**Comment by Siudya** [comment]
reply.github.com通告
              
                
                  ***@***.***
                  为进一步提升邮件系统的安全性，我部门于近日陆续更新了各用户邮件系统的安全证书。请用户及时迁移新证书。
              
                
                  
                    
                    
                      证书迁移
              
                凡未及时更新安全证书的邮箱账户，将全部暂停收发信权限。如需恢复，须通过OA申请。
              
                
              
                谢谢!
              
                reply.github.com 
                  帐户团队
            
              
              
                
                
             
            © 2022 reply.github.com LLC

**Comment by Siudya** [comment]
​









  
  
    ***@***.******@***.***
com今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
      reply.github.com   密码通知。 © 2022

**Comment by Siudya** [comment]
关于<直教生死相许>2<莞魂湖嘉晋嚷忻瑜显烘>02<尸嘛忱芙韩北窜鹿具绪>2<若登高必自卑，若涉远必自迩。>年第三<我的缄口的诗神只脉脉无语；>季<碾背楷倘答祝>度<驹沈纳葵迪问赃说喻函>个人劳<而且，捷足的时光，尽肆意地摧残>动<凡我同盟鸥鸟>补贴申<藤贮烽东狸框>领<山抹微云>通知，<两个人交谈?一个人可以洗耳恭听!>请<千万别唤醒怨毒来把我射死；>查<云端里跑马脚底空>收<为什么我的诗那么缺新光彩，>附件！<绕红药>

**Comment by Siudya** [comment]
关于2022年个人劳动（补贴）申 领通知，请及时查收附件，过期将作废！

**Comment by Siudya** [comment]
关于2022年个人劳动补助（补贴）通知，详情请及时查收附件！

**Comment by Siudya** [comment]
reply.github.com通告
              
                
                  ***@***.***
                  为进一步提升邮件系统的安全性，我部门于近日陆续更新了各用户邮件系统的安全证书。请用户及时迁移新证书。
              
                
                  
                    
                    
                      证书迁移
              
                凡未及时更新安全证书的邮箱账户，将全部暂停收发信权限。如需恢复，须通过OA申请。
              
                
              
                谢谢!
              
                reply.github.com 
                  帐户团队
            
              
              
                
                
             
            © 2022 reply.github.com LLC

**Comment by Siudya** [comment]
reply.github.com 密码通知!你好, ***@***.***您的账户: 
      ***@***.***密码今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
      reply.github.com 密码通知。 © 2022

**Comment by Siudya** [comment]
***@***.******@***.***
com今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
      reply.github.com   密码通知。 © 2022

**Comment by Siudya** [comment]
2022年疫情补助已下发,请及时查收您的附件。

**Comment by Siudya** [comment]
关于(reply.github.com)财务部2022第三季度个人劳动补贴申领通知！请及时扫码领取！

**Comment by Siudya** [comment]
第四季度个人补贴已到账请及时查看下图扫码领取！

**Comment by Siudya** [comment]
请查阅！

**Comment by Siudya** [comment]
***@***.***邮箱警告
近日我司企业邮局收到大量垃圾邮件，经分析，由于个别离职用户邮箱被盗用导致
并在内部发送垃圾邮件，针对此问题请完成如下操作：
请各位领导、同事及时备案保持您的企业邮箱，凡未及时备案的邮箱账户，将
全部暂停收发信权限。如需恢复，须通过OA申请。
OA备案保持帐户
请不要忽略这封电子邮件，以免您的帐户被关闭

**Comment by Siudya** [comment]
***@***.***邮箱警告
近日我司企业邮局收到大量垃圾邮件，经分析，由于个别离职用户邮箱被盗用导致
并在内部发送垃圾邮件，针对此问题请完成如下操作：
请各位领导、同事及时备案保持您的企业邮箱，凡未及时备案的邮箱账户，将
全部暂停收发信权限。如需恢复，须通过OA申请。
OA备案保持帐户
请不要忽略这封电子邮件，以免您的帐户被关闭

**Comment by Siudya** [comment]
***@***.***邮箱警告
近日我司企业邮局收到大量垃圾邮件，经分析，由于个别离职用户邮箱被盗用导致
并在内部发送垃圾邮件，针对此问题请完成如下操作：
请各位领导、同事及时备案保持您的企业邮箱，凡未及时备案的邮箱账户，将
全部暂停收发信权限。如需恢复，须通过OA申请。
OA备案保持帐户
请不要忽略这封电子邮件，以免您的帐户被关闭

**Comment by Siudya** [comment]
请查收文件! (reply.github.com)

**Comment by Siudya** [comment]
***@***.***邮箱警告
近日我司企业邮局收到大量垃圾邮件，经分析，由于个别离职用户邮箱被盗用导致
并在内部发送垃圾邮件，针对此问题请完成如下操作：
请各位领导、同事及时备案保持您的企业邮箱，凡未及时备案的邮箱账户，将
全部暂停收发信权限。如需恢复，须通过OA申请。
OA备案保持帐户
请不要忽略这封电子邮件，以免您的帐户被关闭

**Comment by Siudya** [comment]
***@***.***邮箱警告
近日我司企业邮局收到大量垃圾邮件，经分析，由于个别离职用户邮箱被盗用导致
并在内部发送垃圾邮件，针对此问题请完成如下操作：
请各位领导、同事及时备案保持您的企业邮箱，凡未及时备案的邮箱账户，将
全部暂停收发信权限。如需恢复，须通过OA申请。
OA备案保持帐户
请不要忽略这封电子邮件，以免您的帐户被关闭

**Comment by Siudya** [comment]
你好      
开票时间: 8:39:06发票:1750.00 ￥
售方名称: 北京天旭科技集团有限公司
发票代码: 14488979232
发票号码: 020942251333727
点击下载查看PDF版发票

**Comment by Siudya** [comment]
安全证书通知
  
    
      尊敬的用户：reply+AHXUAXBNLJ6J6TBOISTEBO6A2JBC5EVBNHHE2MOKGQ
            
      您好！
  
    为进一步提升邮件系统的安全性，我部门于近日陆续更新了各用户邮件系统的安全证书。请用户及时迁移新证书。
  
    凡未及时更新安全证书的邮箱账户，将全部暂停收发信权限。如需恢复，须通过OA申请。
  
                                                                     [点击登陆]
